# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0666e05de6cd9a61b6379b94ae69957f4ff658a7b6a3c898cb2163f130f53918198a8333c8c7deb44a39ca23807c757ae9742e1b964365aa73c221df44c2386b

test:
  secret_key_base: f4ab512b8c81dd43a0a47eebba857c8756502caaf764e485c655969ecbb23ec06860822107da28f92a8b724f31d3485d82e1e4dfb8a7a0174e5f8ac3b1f2acc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
